name: CI Builds

on:
  push:
    branches:
      - main
  schedule:
    # Every monday
    - cron:  '0 0 * * MON'

jobs:

  ResInsight:
    name: ResInsight
    runs-on: macos-15
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Build and Install
        run: |
          brew install -v --head SoilRos/OPM/ResInsight
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ResInsight
          path: /opt/homebrew/Cellar/resinsight/*/ResInsight.app
